---
name: Unit Tests

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore:
      - '**'
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, dev, stage]

###############
# Set the Job #
###############
jobs:
  UnitTest:
    name: Unit Test Cases
    # Set the agent to run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Use the appropriate  Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple tdei-gtfs-csv-validator==0.0.31

      - name: Run unit tests
        run: |
          python test_report.py
          coverage run --source=src -m unittest discover -s tests/
          coverage xml
          

      - name: Check coverage
        run: |
          coverage report --fail-under=75
