name: Run Python Tests
on:
  push:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple tdei-gtfs-csv-validator==0.0.31
      - name: Creating Env file
        run: |
          touch .env
          echo PROVIDER=Azure >> .env
          echo UPLOAD_TOPIC=test_subscription_topic >> .env
          echo VALIDATION_TOPIC=test_subscription_topic >> .env
          echo UPLOAD_SUBSCRIPTION=test_subscription >> .env
          echo STORAGECONNECTION='DefaultEndpointsProtocol=https;AccountName=tdeisamplestorage;AccountKey=l9JSJCGq9NrXqRVKApSk1wwV27aWaOVuxeY0NWOZz2svIlJzyncr3UFTzLoAanFbmJIeb2WmwIcS+AStj5gELg==;EndpointSuffix=core.windows.net' >> .env
          echo QUEUECONNECTION='Endpoint=sb://tdei-service-bus.servicebus.windows.net/;SharedAccessKeyName=developer;SharedAccessKey=bddlcZHcH3sos3izTIYyaZTpapFRoVHwjOkfCZPdSxk=;EntityPath=gtfs-flex-upload' >> .env
      - name: Run tests
        run: |
          coverage run --source=src -m unittest discover -s tests
      - name: Test Report
        run: |
          coverage report
